# Generated by Django 5.0.4 on 2024-06-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetrack',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='pricetrack',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariantaffiliate'),
        ),
        migrations.AddField(
            model_name='productvariantaffiliate',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
