# Generated by Django 5.0.4 on 2024-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_feature_value_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='mrp',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='official_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
