# Generated by Django 5.0.4 on 2024-06-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productvariant_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='value_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
