# Generated by Django 5.0.4 on 2024-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
