# Generated by Django 5.0.4 on 2024-04-24 05:20

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('seo_title', models.TextField(blank=True, max_length=100, null=True)),
                ('seo_description', models.TextField(blank=True, max_length=255, null=True)),
                ('detail', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/')),
                ('views', models.IntegerField(default=0)),
                ('read_time', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='tag.tag')),
            ],
        ),
    ]
