# Generated by Django 5.0.4 on 2024-05-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='end_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='start_price',
            field=models.IntegerField(default=0),
        ),
    ]
