# Generated by Django 5.0.6 on 2024-07-10 13:21

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='md/blog/'),
        ),
    ]
